version: "3"
services:
  db: 
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
  app: 
    image: my-node-app
    ports:
      - "13000:3000"

